--CRIAÇÃO DE UM USUARIO PARA ACESSAR O BANCO
CREATE LOGIN alunoFS13
WITH PASSWORD = '1234';

--ATRIBUINDO O PERFIL DO LOGIN ALUNO PARA O USUARIO
CREATE USER alunoFS13 FOR LOGIN alunoFS13;

--ATRIBUINDO PERMISSAO APENAS PARA SELECT A ESSE USUARIO
GRANT SELECT TO alunoFS13;